### PR TITLE
Added lives functionality

### PR DESCRIPTION
**Pull request by mennoo1996**
For one level only, since there is only one level yet

### CODE REVIEW

**Comment by mennoo1996** [comment]
Don't mind the  "een commit #1", this was used for testing purposes at the start of the project

**Comment by bart-de-jonge** [comment]
Why are you using the boolean playerIntersect? If the player collides with a bubble, the game will re-enter the gamestate or procede to the gamOverState. So is the boolean necessary?

**Comment by StefanV7** [comment]
It isn't necessary if the state is IMMEDIATLY changed. Originally it was to ensure that when you kept playing the level, it wouldn't subtract multiple level for the same hit.

**Comment by bart-de-jonge** [comment]
Most of the time, the state is changed immediatly right? Or have you encountered the problem where multiple lives where subtracted for the same hit? If so, nice solution, if not, maybe test if it can be removed as it is overhead and redundant code in that case. For now I will merge the code.

**Pull request merged**
