### PR TITLE
Code review s2

### PR DESCRIPTION
**Pull request by StefanV7**
More refactor stuff, not a lot.
<layout,logic,organisation

### CODE REVIEW

**Comment by Markvanderuit** [comment]
The new behavior of Weapon.update() is NOT the same as before. Now, if visible was already false, it can be switched to true instead. This might cause some unpredictable behavior. Can you check this?

<review

**Comment by StefanV7** [comment]
Yes, with Alex. He says that it begins on visible and that that is the only spot where it changes.
<logic

**Comment by Markvanderuit** [comment]
Oh, that's cool. Looks good, then!

<review

**Comment by bart-de-jonge** [comment]
Well done!
<review

**Pull request merged**
