### PR TITLE
Pickups lan3

### PR DESCRIPTION
**Pull request by StefanV7**
More pickup handling, the host can succesfully make items drop & pick them up on both screens.
The client can probably pick up stuff correctly as well, however not make stuff drop yet.
<feature,organisation

### CODE REVIEW

**Comment by mennoo1996** [comment]
Why did you change the chances for coin and powerup?
<review

**Comment by StefanV7** [comment]
To make testing a whole lot easier, can be changed back easily
<logic

**Comment by mennoo1996** [comment]
Please do so before merging into master
<review

**Comment by Markvanderuit** [comment]
@Stefan1de1V will merge as soon as chances are changed back. Otherwise, looks good!
<review

**Comment by mennoo1996** [comment]
Thank you, will merge. I expect the travis review to succeed
<review, feature

**Pull request merged**
