### PR TITLE
Iterator s2

### PR DESCRIPTION
**Pull request by StefanV7**
The GameStateGateHelper now has a GateList object instead of ArrayList<Gate>. The GateList can give an iterator which is used instead of a for-loop. Only the levelContainer uses an ArrayList<Gate>, and from now on a GateList is preferred.
<organisation,layout,documentation

### CODE REVIEW

**Comment by Markvanderuit** [comment]
Looks good. The why baffles me though. Is this for the pattern?

<review

**Comment by StefanV7** [comment]
Yup. GateList as a class has a createIterator() method and instead of a for-loop the iterator & a while loop can be used (iterator pattern).
<organisation

**Comment by Markvanderuit** [comment]
Ah, ok that makes a lot of sense. Waiting for second person to merge.
<review

**Comment by bart-de-jonge** [comment]
Well done!
<review

**Pull request merged**
